apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-server
  namespace: x-road  # Añadir el namespace aquí
  labels:
    app: central-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central-server
  template:
    metadata: 
      labels: 
        app: central-server
    spec:
      containers:
      - name: central-server
        image: niis/xroad-central-server:jammy-7.3.2
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "2"

---

apiVersion: v1
kind: Service
metadata:
  name: central-server-service
  namespace: x-road
spec:
  type: NodePort
  selector:
    app: central-server
  ports:
    - name: http-4000  # Nombre para el puerto 4000
      protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30001
    - name: http-8181  # Nombre para el puerto 8181
      protocol: TCP
      port: 8181
      targetPort: 80
      nodePort: 30002
    - name: http-9998  # Nombre para el puerto 9998
      protocol: TCP
      port: 9998
      targetPort: 9998
      nodePort: 30003
