apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central-server
  template:
    metadata:
      labels:
        app: central-server
    spec:
      containers:
      - name: central-server
        image: niis/xroad-central-server:jammy-7.3.2
        ports:
        - containerPort: 4000
        - containerPort: 80
        - containerPort: 9998
        volumeMounts:
        - mountPath: /etc/xroad
          name: central-server-conf
        - mountPath: /var/lib/xroad
          name: central-server-data
        - mountPath: /var/log/xroad
          name: central-server-logs
        - mountPath: /var/lib/postgresql/data
          name: central-server-db
      volumes:
      - name: central-server-conf
        emptyDir: {}
      - name: central-server-data
        emptyDir: {}
      - name: central-server-logs
        emptyDir: {}
      - name: central-server-db
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: central-server-service
spec:
  selector:
    app: central-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
