name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up K8s
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Set up Minikube
      uses: manusa/actions-setup-minikube@v2.4.0
      with:
        minikube version: 'latest'

    - name: Deploy to Minikube
      run: |
        kubectl apply -f deployments/central-server-deployment.yaml
        kubectl apply -f deployments/central-server-service.yaml
        kubectl apply -f deployments/transito-security-server-deployment.yaml
        kubectl apply -f deployments/transito-security-server-service.yaml
        kubectl apply -f deployments/tecnologia-security-server-deployment.yaml
        kubectl apply -f deployments/tecnologia-security-server-service.yaml
        kubectl apply -f deployments/dni-security-server-deployment.yaml
        kubectl apply -f deployments/dni-security-server-service.yaml
