name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Minikube
      run: |
        kubectl apply -f deployments/central-server-deployment.yaml -ns x-road
        kubectl apply -f deployments/central-server-service.yaml -ns x-road
        kubectl apply -f deployments/transito-security-server-deployment.yaml -ns x-road
        kubectl apply -f deployments/transito-security-server-service.yaml -ns x-road
        kubectl apply -f deployments/tecnologia-security-server-deployment.yaml -ns x-road
        kubectl apply -f deployments/tecnologia-security-server-service.yaml -ns x-road
        kubectl apply -f deployments/dni-security-server-deployment.yaml -ns x-road
        kubectl apply -f deployments/dni-security-server-service.yaml -ns x-road
