name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Minikube
      run: |
        kubectl apply -f /home/mbarrionuevo/transito/k8s-xroad/deployments/central-server-deployment.yaml -n x-road
        kubectl apply -f /home/mbarrionuevo/transito/k8s-xroad/deployments/central-server-service.yaml -n x-road
        kubectl apply -f /home/mbarrionuevo/transito/k8s-xroad/deployments/transito-security-server-deployment.yaml -n x-road
        kubectl apply -f /home/mbarrionuevo/transito/k8s-xroad/deployments/transito-security-server-service.yaml -n x-road
        kubectl apply -f /home/mbarrionuevo/transito/k8s-xroad/deployments/tecnologia-security-server-deployment.yaml -n x-road
        kubectl apply -f /home/mbarrionuevo/transito/k8s-xroad/deployments/tecnologia-security-server-service.yaml -n x-road
        kubectl apply -f /home/mbarrionuevo/transito/k8s-xroad/deployments/dni-security-server-deployment.yaml -n x-road
        kubectl apply -f /home/mbarrionuevo/transito/k8s-xroad/deployments/dni-security-server-service.yaml -n x-road
